# Generated by Django 4.2.17 on 2025-07-29 20:51

import datetime
from django.db import migrations, models


def make_unordered_order_dates_null(apps, schema_editor):
    """Set order_date to null if ordered is False - prepare for removing ordered field"""
    Order = apps.get_model("inventory", "Order")
    unordered_orders = Order.objects.filter(ordered=False)
    unordered_orders.update(order_date=None)


def make_unordered_order_dates_not_null(apps, schema_editor):
    """Set order_date to created date if ordered is False (reverses above migration)"""
    Order = apps.get_model("inventory", "Order")
    for order in Order.objects.filter(order_date__isnull=True):
        order.order_date = order.created.date
        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_add_uniqueness_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.RunPython(
            make_unordered_order_dates_null, make_unordered_order_dates_not_null
        ),
    ]
