# Generated by Django 4.2.17 on 2025-07-29 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_order_order_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_date",
            new_name="ordered_on",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="date_arrived",
            new_name="arrived_on",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ordered",
        ),
    ]
