# Generated by Django 4.2.17 on 2025-07-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_remove_item_date_added_item_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ordered_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
