# Generated by Django 4.2.17 on 2025-07-29 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_alter_order_ordered_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ordered_by",
            new_name="placed_by",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="ordered_on",
            new_name="placed_on",
        ),
    ]
