# Generated by Django 5.1.4 on 2025-08-11 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_rename_ordered_by_order_placed_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="placed_by", new_name="requested_by"
        ),
    ]
