# Generated by Django 5.1.4 on 2025-08-11 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_auto_20250811_1413"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="expires",
            new_name="expires_on",
        ),
        migrations.AlterField(
            model_name="order",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Requested by",
            ),
        ),
    ]
