# Generated by Django 5.2.9 on 2025-12-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_stockitem_checkoutrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutrecord',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
